2021-11-04 10:41:02,284 data_manager.py[line:1364] INFO {'############################发送抽水数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '', 'capacity': '1000', 'deep': 0.5, 'bottleNum': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-04 10:41:43,001 data_manager.py[line:1364] INFO {'############################发送抽水数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '', 'capacity': '1000', 'deep': 0.5, 'bottleNum': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-04 10:41:50,250 data_manager.py[line:1364] INFO {'############################发送抽水数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '', 'capacity': '1000', 'deep': 0.5, 'bottleNum': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-04 10:43:59,429 data_manager.py[line:1365] INFO {'############################发送抽水数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '', 'capacity': '1000', 'deep': 0.5, 'bottleNum': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-04 12:58:01,521 data_manager.py[line:1372] INFO {'############################发送抽水数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '', 'capacity': '1000', 'deep': 0.5, 'bottleNum': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-09 18:19:08,250 data_manager.py[line:1451] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.523823, 30.506091]', 'gjwd': '[114.523823, 30.506091]'}}
2021-11-09 18:30:32,989 data_manager.py[line:1452] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.523823, 30.506089]', 'gjwd': '[114.523823, 30.506089]'}}
2021-11-09 18:37:42,540 data_manager.py[line:1453] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.52414, 30.506472]', 'gjwd': '[114.524149, 30.506511]'}}
2021-11-09 18:37:48,771 data_manager.py[line:1453] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.52382, 30.506088]', 'gjwd': '[114.52382, 30.506088]'}}
2021-11-09 18:41:07,201 data_manager.py[line:1454] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524147, 30.506504]', 'gjwd': '[114.524145, 30.506509]'}}
2021-11-09 18:41:13,414 data_manager.py[line:1454] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.52382, 30.506088]', 'gjwd': '[114.52382, 30.506088]'}}
2021-11-09 18:44:05,528 data_manager.py[line:1454] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524132, 30.506465]', 'gjwd': '[114.524149, 30.506512]'}}
2021-11-09 18:44:11,760 data_manager.py[line:1454] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.523823, 30.506089]', 'gjwd': '[114.523823, 30.506089]'}}
2021-11-09 19:38:36,791 data_manager.py[line:1455] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524151, 30.506513]', 'gjwd': '[114.524151, 30.506513]'}}
2021-11-09 19:38:45,229 data_manager.py[line:1455] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.52382, 30.506088]', 'gjwd': '[114.52382, 30.506088]'}}
2021-11-09 19:45:46,773 data_manager.py[line:1450] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022B5C967A08>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-09 19:45:46,787 data_manager.py[line:1451] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524133, 30.506495]', 'gjwd': '[114.524133, 30.506495]'}}
2021-11-09 19:51:35,123 data_manager.py[line:1454] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021ED7306708>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-09 19:51:35,124 data_manager.py[line:1455] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524136, 30.506503]', 'gjwd': '[114.524136, 30.506503]'}}
2021-11-09 19:53:24,328 data_manager.py[line:1456] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017BBD7A1348>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-09 19:53:24,341 data_manager.py[line:1457] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.52415, 30.506513]', 'gjwd': '[114.52415, 30.506513]'}}
2021-11-09 19:53:53,747 data_manager.py[line:1456] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017BBD798648>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-09 19:53:53,808 data_manager.py[line:1457] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.523821, 30.506092]', 'gjwd': '[114.523821, 30.506092]'}}
2021-11-09 19:59:15,790 data_manager.py[line:1454] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000280FFFA6808>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-09 19:59:15,805 data_manager.py[line:1455] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.523816, 30.50609]', 'gjwd': '[114.523816, 30.50609]'}}
2021-11-09 19:59:41,107 data_manager.py[line:1454] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000280FFFB1108>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-09 19:59:41,109 data_manager.py[line:1455] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524142, 30.506476]', 'gjwd': '[114.524142, 30.506476]'}}
2021-11-10 08:52:39,063 data_manager.py[line:1453] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D580CA22C8>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-10 08:52:39,076 data_manager.py[line:1454] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524147, 30.50651]', 'gjwd': '[114.524147, 30.50651]'}}
2021-11-10 08:53:06,176 data_manager.py[line:1453] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D580C8ED08>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-10 08:53:06,188 data_manager.py[line:1454] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.523822, 30.50609]', 'gjwd': '[114.523822, 30.50609]'}}
2021-11-10 09:14:12,041 data_manager.py[line:1454] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D9CEE8FA48>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-10 09:14:12,071 data_manager.py[line:1455] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-10 09:14:37,183 data_manager.py[line:1454] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D9CEE8F548>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-10 09:14:37,195 data_manager.py[line:1455] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-10 09:15:04,328 data_manager.py[line:1454] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D9CEE61208>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-10 09:15:04,340 data_manager.py[line:1455] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-10 09:15:29,449 data_manager.py[line:1454] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D9CEE92A48>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-10 09:15:29,456 data_manager.py[line:1455] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-10 09:15:56,572 data_manager.py[line:1454] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D9CEE92D88>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-10 09:15:56,584 data_manager.py[line:1455] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-10 09:16:21,703 data_manager.py[line:1454] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D9CEE8FBC8>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-10 09:16:21,708 data_manager.py[line:1455] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-10 09:16:46,799 data_manager.py[line:1454] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D9CEE92948>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-10 09:16:46,811 data_manager.py[line:1455] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-10 09:27:45,102 data_manager.py[line:1454] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ED719CEAC8>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-10 09:27:45,114 data_manager.py[line:1455] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-10 09:37:22,856 data_manager.py[line:1454] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ED719A5288>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-10 09:37:22,868 data_manager.py[line:1455] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-10 09:37:50,010 data_manager.py[line:1454] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ED719BB6C8>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-10 09:37:50,022 data_manager.py[line:1455] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-10 09:38:15,688 data_manager.py[line:1454] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ED7188FA88>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-10 09:38:15,694 data_manager.py[line:1455] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-10 09:38:40,804 data_manager.py[line:1454] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ED71AB6048>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-10 09:38:40,816 data_manager.py[line:1455] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-10 09:39:05,948 data_manager.py[line:1454] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ED71AB6CC8>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-10 09:39:05,954 data_manager.py[line:1455] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-10 09:39:33,066 data_manager.py[line:1454] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ED71AB6F88>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-10 09:39:33,078 data_manager.py[line:1455] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-10 09:39:58,161 data_manager.py[line:1454] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ED719A5BC8>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-10 09:39:58,173 data_manager.py[line:1455] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-10 09:40:23,265 data_manager.py[line:1454] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ED71AB2F88>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-10 09:40:23,277 data_manager.py[line:1455] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-10 09:40:50,383 data_manager.py[line:1454] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ED71AB6508>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-10 09:40:50,395 data_manager.py[line:1455] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-10 09:41:15,505 data_manager.py[line:1454] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ED71884588>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-10 09:41:15,517 data_manager.py[line:1455] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-10 09:41:40,625 data_manager.py[line:1454] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ED71AB6188>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-10 09:41:40,637 data_manager.py[line:1455] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-10 09:42:07,745 data_manager.py[line:1454] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ED71AB2C08>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-10 09:42:07,757 data_manager.py[line:1455] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-10 09:42:32,876 data_manager.py[line:1454] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ED719A5088>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-10 09:42:32,888 data_manager.py[line:1455] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-10 09:42:57,998 data_manager.py[line:1454] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ED71AB2E48>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-10 09:42:58,028 data_manager.py[line:1455] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-10 09:43:25,146 data_manager.py[line:1454] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ED719A5648>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-10 09:43:25,158 data_manager.py[line:1455] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-10 09:43:50,269 data_manager.py[line:1454] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ED7188F308>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-10 09:43:50,281 data_manager.py[line:1455] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-10 09:44:15,390 data_manager.py[line:1454] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ED71AB65C8>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-10 09:44:15,402 data_manager.py[line:1455] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-10 09:44:42,782 data_manager.py[line:1454] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ED7181F288>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-10 09:44:42,805 data_manager.py[line:1455] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-10 09:45:07,914 data_manager.py[line:1454] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ED71AB2088>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-10 09:45:07,926 data_manager.py[line:1455] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-10 09:45:33,016 data_manager.py[line:1454] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ED7181F288>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-10 09:45:33,034 data_manager.py[line:1455] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-10 09:46:00,155 data_manager.py[line:1454] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ED71AB6448>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-10 09:46:00,167 data_manager.py[line:1455] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-10 09:46:25,267 data_manager.py[line:1454] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ED719BB288>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-10 09:46:25,279 data_manager.py[line:1455] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-10 09:46:52,386 data_manager.py[line:1454] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ED71AB6048>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-10 09:46:52,392 data_manager.py[line:1455] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-10 09:47:18,011 data_manager.py[line:1454] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ED718847C8>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-10 09:47:18,017 data_manager.py[line:1455] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-10 09:47:43,119 data_manager.py[line:1454] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ED71AB6208>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-10 09:47:43,131 data_manager.py[line:1455] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-10 09:48:08,536 data_manager.py[line:1454] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ED71AB6348>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-10 09:48:08,542 data_manager.py[line:1455] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-10 09:48:33,652 data_manager.py[line:1454] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ED71AB2D08>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-10 09:48:33,664 data_manager.py[line:1455] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-10 09:49:00,769 data_manager.py[line:1454] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ED7188FFC8>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-10 09:49:00,787 data_manager.py[line:1455] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-10 09:49:25,898 data_manager.py[line:1454] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ED719CE688>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-10 09:49:25,910 data_manager.py[line:1455] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-10 09:49:53,013 data_manager.py[line:1454] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ED71AB6888>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-10 09:49:53,031 data_manager.py[line:1455] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-10 09:50:18,132 data_manager.py[line:1454] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ED71AB26C8>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-10 09:50:18,144 data_manager.py[line:1455] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-10 09:50:43,249 data_manager.py[line:1454] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ED719BB248>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-10 09:50:43,261 data_manager.py[line:1455] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-10 09:51:10,407 data_manager.py[line:1454] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ED719CE1C8>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-10 09:51:10,425 data_manager.py[line:1455] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-10 09:51:35,581 data_manager.py[line:1454] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ED71AB63C8>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-10 09:51:35,593 data_manager.py[line:1455] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-10 09:52:01,080 data_manager.py[line:1454] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ED719CE848>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-10 09:52:01,086 data_manager.py[line:1455] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-10 09:52:26,194 data_manager.py[line:1454] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ED719BB048>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-10 09:52:26,206 data_manager.py[line:1455] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-10 09:52:53,314 data_manager.py[line:1454] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ED7188F208>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-10 09:52:53,326 data_manager.py[line:1455] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-10 09:53:18,433 data_manager.py[line:1454] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ED71AB6348>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-10 09:53:18,445 data_manager.py[line:1455] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-10 09:53:43,540 data_manager.py[line:1454] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ED719BBF88>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-10 09:53:43,552 data_manager.py[line:1455] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-10 09:54:10,663 data_manager.py[line:1454] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ED71884948>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-10 09:54:10,675 data_manager.py[line:1455] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-10 09:54:35,778 data_manager.py[line:1454] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ED7188F6C8>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-10 09:54:35,790 data_manager.py[line:1455] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-10 09:55:00,938 data_manager.py[line:1454] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ED71AB26C8>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-10 09:55:00,945 data_manager.py[line:1455] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-10 09:55:28,049 data_manager.py[line:1454] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ED71AB2908>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-10 09:55:28,060 data_manager.py[line:1455] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-10 11:22:34,219 data_manager.py[line:1473] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F4AD736908>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-10 11:22:34,231 data_manager.py[line:1474] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-10 11:22:59,335 data_manager.py[line:1473] INFO {'发送检测数据error': ConnectionError(MaxRetryError("HTTPConnectionPool(host='192.168.199.186', port=8009): Max retries exceeded with url: /union/admin/xxl/data/sampling/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F4AD950BC8>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))"))}
2021-11-10 11:22:59,347 data_manager.py[line:1474] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524049, 30.506765]', 'gjwd': '[114.524049, 30.506765]'}}
2021-11-12 09:52:41,363 data_manager.py[line:1488] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-12 09:52:45,573 data_manager.py[line:1488] INFO {'发送检测数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 1000, 'deep': 0.5, 'bottle_num': 0, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-12 10:03:56,750 data_manager.py[line:1493] INFO {'发送采样数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 200, 'deep': 0.1, 'bottle_num': 2, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-12 10:04:02,989 data_manager.py[line:1493] INFO {'发送采样数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 200, 'deep': 0.1, 'bottle_num': 2, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-12 10:04:07,219 data_manager.py[line:1493] INFO {'发送采样数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 200, 'deep': 0.1, 'bottle_num': 2, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-12 10:04:13,452 data_manager.py[line:1493] INFO {'发送采样数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 200, 'deep': 0.1, 'bottle_num': 2, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-12 10:06:55,081 data_manager.py[line:1494] INFO {'发送采样数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 200, 'deep': 0.1, 'bottle_num': 2, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-12 10:10:28,919 data_manager.py[line:1494] INFO {'发送采样数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 200, 'deep': 0.1, 'bottle_num': 2, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
2021-11-12 10:16:09,987 data_manager.py[line:1494] INFO {'发送采样数据': {'deviceId': 'XXLJC4LCGSCSD1DA002', 'mapId': '1434770242236428290', 'capacity': 200, 'deep': 0.1, 'bottle_num': 1, 'jwd': '[114.524096, 30.506853]', 'gjwd': '[114.524096, 30.506853]'}}
